// Generated by CoffeeScript 1.6.3
(function() {
  var HttpStatus, JsUrl, XhrReadyState, eval_url;

  HttpStatus = {
    ok: 200,
    not_modified: 304
  };

  XhrReadyState = {
    complete: 4
  };

  JsUrl = {
    local: '/catincanlib.js',
    remote: 'https://dl.catincan.com/catincanlib.js'
  };

  eval_url = function(url, success, failure) {
    var xhr;
    if (success == null) {
      success = null;
    }
    if (failure == null) {
      failure = null;
    }
    xhr = new XMLHttpRequest();
    xhr.addEventListener('readystatechange', function() {
      if (xhr.readyState === XhrReadyState.complete) {
        if (xhr.status === HttpStatus.ok || xhr.status === HttpStatus.not_modified) {
          if (success) {
            success(url);
          }
          return eval(xhr.responseText);
        } else {
          if (failure) {
            return failure(url);
          }
        }
      }
    });
    xhr.open('GET', url, true);
    return xhr.send();
  };

  eval_url(JsUrl.local, function(url) {
    return console.log("Using local JS: " + url);
  }, function(url) {
    return eval_url(JsUrl.remote, null, function(url) {
      return console.log("Failed to load remote JS: " + url);
    });
  });

}).call(this);
